export enum NODE_SPECIAL_BYTE {
    START                               = 0xFE,
    END                                 = 0xFF,
    ESCAPE_CHAR                         = 0xFD
}

export enum ITEM_GROUP {
    NONE,
    GROUND,
    CONTAINER,
    WEAPON,
    AMMUNITION,
    ARMOR,
    RUNE,
    TELEPORT,
    MAGICFIELD,
    WRITABLE,
    KEY,
    SPLASH,
    FLUID,
    DOOR,
    DEPRECATED,
    LAST
}

export enum ITEM_TYPE {
    NONE,
    DEPOT,
    MAILBOX,
    TRASHHOLDER,
    CONTAINER,
    DOOR,
    MAGICFIELD,
    TELEPORT,
    BED,
    KEY,
    LAST
}

export enum FLAG {
    UNPASSABLE                          = 1 << 0,
    BLOCK_MISSILES                      = 1 << 1,
    BLOCK_PATHFINDER                    = 1 << 2,
    HAS_ELEVATION                       = 1 << 3,
    USEABLE                             = 1 << 4,
    PICKUPABLE                          = 1 << 5,
    MOVEABLE                            = 1 << 6,
    STACKABLE                           = 1 << 7,
    FLOORCHANGEDOWN                     = 1 << 8,
    FLOORCHANGENORTH                    = 1 << 9,
    FLOORCHANGEEAST                     = 1 << 10,
    FLOORCHANGESOUTH                    = 1 << 11,
    FLOORCHANGEWEST                     = 1 << 12,
    ALWAYSONTOP                         = 1 << 13,
    READABLE                            = 1 << 14,
    ROTABLE                             = 1 << 15,
    HANGABLE                            = 1 << 16,
    HOOK_EAST                           = 1 << 17,
    HOOK_SOUTH                          = 1 << 18,
    CANNOTDECAY                         = 1 << 19,
    ALLOWDISTREAD                       = 1 << 20,
    UNUSED                              = 1 << 21,
    CLIENTCHARGES                       = 1 << 22,
    IGNORE_LOOK                         = 1 << 23,
    IS_ANIMATION                        = 1 << 24,
    FULL_GROUND                         = 1 << 25,
    FORCE_USE                           = 1 << 26
}

export enum FLAG_NAME {
    UNPASSABLE                          = 'unpassable',
    BLOCK_MISSILES                      = 'blockMissiles',
    BLOCK_PATHFINDER                    = 'blockPathfinder',
    HAS_ELEVATION                       = 'hasElevation',
    USEABLE                             = 'useable',
    PICKUPABLE                          = 'pickupable',
    MOVEABLE                            = 'moveable',
    STACKABLE                           = 'stackable',
    FLOORCHANGEDOWN                     = 'floorChangeDown',
    FLOORCHANGENORTH                    = 'floorChangeNorth',
    FLOORCHANGEEAST                     = 'floorChangeEast',
    FLOORCHANGESOUTH                    = 'floorChangeSouth',
    FLOORCHANGEWEST                     = 'floorChangeWest',
    ALWAYSONTOP                         = 'alwaysOnTop',
    HANGABLE                            = 'hangable',
    HOOK_EAST                           = 'hookEast',
    HOOK_SOUTH                          = 'hookSouth',
    ALLOWDISTREAD                       = 'allowDistRead',
    ROTABLE                             = 'rotatable',
    READABLE                            = 'readable',
    CLIENTCHARGES                       = 'clientChargeable',
    IGNORE_LOOK                         = 'ignoreLook',
    IS_ANIMATION                        = 'isAnimation',
    FULL_GROUND                         = 'fullGround',
    FORCE_USE                           = 'forceUse'
}

export enum ITEM_ATTRIBUTE_NAME {
    SERVERID = 'serverId',
    CLIENT_ID = 'clientId',
    NAME = 'name',
    DESCRIPTION = 'description',
    SPRITEHASH = 'spriteHash',
    SPEED = 'speed',
    LIGHT_LEVEL = 'lightLevel',
    LIGHT_COLOR = 'lightColor',
    TOPORDER = 'alwaysOnTopOrder',
    MAXITEMS = 'capacity',
    WEIGHT = "weight",
    MINIMAPCOLOR = 'minimapColor',
    ROTATETO = 'rotateTo',
    MAX_WRITE_LENGTH = 'maxWriteLength',
    MAX_READ_LENGTH = 'maxReadLength'
}

export enum ITEM_ATTRIBUTE {
    SERVERID = 16,
    CLIENT_ID,
    NAME,
    DESCRIPTION,
    SPEED,
    SLOT,
    MAXITEMS,
    WEIGHT,
    WEAPON,
    AMMUNITION,
    ARMOR,
    MAGICLEVEL,
    MAGICFIELDTYPE,
    WRITEABLE,
    ROTATETO,
    DECAY,
    SPRITEHASH,
    MINIMAPCOLOR,
    LIGHT = 36,
    MAX_WRITE_LENGTH = 34,
    MAX_READ_LENGTH,
    DECAY2,
    WEAPON2,
    AMMUNITION2,
    ARMOR2,
    WRITEABLE2,
    LIGHT2,
    LIGHT3,
    TOPORDER
}
